#!/usr/bin/env python3
"""Build the source archive required for Firefox AMO review."""

from __future__ import annotations

import argparse
from pathlib import Path
import zipfile


ROOT = Path(__file__).resolve().parent.parent
EXTENSION = ROOT / "extension"


REQUIRED_FILES = (
    Path("extension") / "build.py",
    Path("extension") / "README.md",
    Path("scripts") / "package_firefox_extension.py",
)


def source_files() -> list[Path]:
    files: list[Path] = []
    for relative_root in (Path("extension/core"), Path("extension/firefox")):
        root = ROOT / relative_root
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(ROOT)
            # Firefox core copies are generated by extension/build.py and are
            # deliberately excluded from the submitted source archive.
            if relative.parts[:3] == ("extension", "firefox", "core"):
                continue
            if "__pycache__" in relative.parts or path.name == ".DS_Store":
                continue
            files.append(path)
    files.extend(ROOT / relative for relative in REQUIRED_FILES if relative not in {path.relative_to(ROOT) for path in files})
    files.append(ROOT / "scripts" / "package_firefox_source.py")
    return sorted(set(files))


def package(output: Path) -> None:
    missing = [relative for relative in REQUIRED_FILES if not (ROOT / relative).is_file()]
    if missing:
        raise RuntimeError("source archive is missing: " + ", ".join(map(str, missing)))

    files = source_files()
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(
        output,
        mode="w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
    ) as archive:
        for path in files:
            relative = path.relative_to(ROOT).as_posix()
            info = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())
    print(f"created {output} ({len(files)} source files)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "dist" / "distraction-blocker-firefox-source.zip",
        help="source archive path",
    )
    args = parser.parse_args()
    package(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
